### ISSUE TITLE
Plugin fails when input file does not include band names within tiff metadata

### ISSUE THREAD

**Issue by lachlanhurst** [ausseabed/ggoutlier-qax-plugin#2]
Band names can be specified in two ways:
- using the band name (description field) within the geotiff metadata
- Including the band name within the filename

The GGOutlier plugin should support both these, however there's on line of code that assumes band names are not None. Code can be found [here](https://github.com/ausseabed/ggoutlier-qax-plugin/blob/1edc29de1445fe16c9f1682076390ea54799738d/ausseabed/ggoutlier/qax/plugin.py#L101).

Excerpt shown below

    band_names = cloud2tif.getbandnames(f.path)
    band_names = list(map(lambda x: x.lower(), band_names))

Issue is that the `cloud2tif.getbandnames` function may include `None` values in the array it returns and the following line will fail if a `None` is present.

**Comment by sixy6e** [comment]
An approach to get around the `None` issue would be to check for `None` within a list comprehension  eg:

```python
band_names = [name.lower() for name in band_names if name is not None]
```

However, it doesn't resolve the issue of depending on a valid band name for the test to continue.

One option is to enforce from a QAX perspective that input GeoTIFF's have band names populated. Unfortunately, this may not be guaranteed by all vendors producing a GeoTIFF.

Another is to handle on the qax side for the user to specify the band number if names are not defined, and if the input GeoTIFF is a multi-band GeoTIFF. For single-band GeoTIFF's, it is solely down to the user specifying the correct file in the first place, and band names can be ignored, as the band number would always be *1*.

It is preferable to avoid imlementing anything on the QAX side to assume anything based on input filenames. That adds unnecessary complexity.

**Comment by sixy6e** [comment]
I do notice that there is existing code to check for the existence of band names:

https://github.com/ausseabed/ggoutlier-qax-plugin/blob/1edc29de1445fe16c9f1682076390ea54799738d/ausseabed/ggoutlier/qax/plugin.py#L234-L259

However, it doesn't fail anything and simply reports back to a higher-level caller, presumably within Qax itself and possibly logged.

**Comment by lachlanhurst** [comment]
> I do notice that there is existing code to check for the existence of band names

This was a quick copy/paste from the other plugins when I realised the GGOutlier plugin wasn't providing summary info. The output of this function ends up being displayed in the qax ui (input file table, details column). Neater solution may be to rework this, but honestly just including a `None` check in the list comprehension as you did would be fine.

**Comment by sixy6e** [comment]
Ah right, and with `grid_file = None` not being modified, the process will fail safely at:

https://github.com/ausseabed/ggoutlier-qax-plugin/blob/1edc29de1445fe16c9f1682076390ea54799738d/ausseabed/ggoutlier/qax/plugin.py#L127-L131
